# Generated by Django 6.0 on 2026-03-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_historicalnotice_historicalnoticecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotice',
            name='important',
            field=models.BooleanField(default=False, null=True, verbose_name='Set Important:'),
        ),
        migrations.AddField(
            model_name='notice',
            name='important',
            field=models.BooleanField(default=False, null=True, verbose_name='Set Important:'),
        ),
    ]
