# Generated by Django 6.0 on 2026-03-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_historicalnotice_important_notice_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='লিঙ্কের নাম (যেমন: MyGov BD)', max_length=100)),
                ('url', models.URLField(help_text='সম্পূর্ণ লিঙ্ক (https://...)', max_length=500)),
                ('svg_icon', models.TextField(blank=True, help_text='এখানে SVG <svg>...</svg> কোডটি পেস্ট করুন', null=True)),
                ('priority', models.IntegerField(default=0, help_text='সিরিয়াল নম্বর (ছোট থেকে বড় সাজানো হবে)')),
                ('is_active', models.BooleanField(default=True, help_text='টিক দেওয়া থাকলে সাইটে দেখাবে')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
