# Generated by Django 6.0 on 2026-03-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_importantlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantlink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='important_links/'),
        ),
    ]
