# Generated by Django 6.0 on 2026-03-27 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0062_alter_order_order_status'),
        ('Website', '0005_importantlink_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='Student Name')),
                ('contact_no', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='বর্তমান ঠিকানা', null=True)),
                ('city', models.CharField(blank=True, help_text='শহর/উপজেলা', max_length=100, null=True)),
                ('last_school_college', models.CharField(blank=True, help_text='পূর্ববর্তী শিক্ষা প্রতিষ্ঠান', max_length=255, null=True)),
                ('query_message', models.TextField(verbose_name='Message/Query Details')),
                ('source', models.CharField(choices=[('website', 'Website'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone Call'), ('walk_in', 'Walk-In'), ('reference', 'Reference')], default='website', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('followed_up', 'Followed Up'), ('admitted', 'Converted/Admitted'), ('cancelled', 'Cancelled/Not Interested')], default='pending', max_length=20)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, help_text='অফিসিয়াল মন্তব্য বা ফলো-আপ আপডেট', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admission_queries', to='MyShop.employeeprofile', verbose_name='Assigned Employee')),
                ('interest_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyShop.program')),
            ],
            options={
                'verbose_name': 'Admission Query',
                'verbose_name_plural': 'Admission Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
