# Generated by Django 6.0 on 2026-03-27 13:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_admissionquery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Slider Title')),
                ('subtitle', models.TextField(blank=True, max_length=500, null=True, verbose_name='Subtitle / Description')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Slider Image')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=50, null=True)),
                ('button_url', models.CharField(blank=True, default='#', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Home Slider',
                'verbose_name_plural': 'Home Sliders',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHomeSlider',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Slider Title')),
                ('subtitle', models.TextField(blank=True, max_length=500, null=True, verbose_name='Subtitle / Description')),
                ('image', models.TextField(max_length=100, verbose_name='Slider Image')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=50, null=True)),
                ('button_url', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Home Slider',
                'verbose_name_plural': 'historical Home Sliders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
