# Generated by Django 6.0 on 2026-03-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_homeslider_historicalhomeslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Home Page, About Us, notice_page', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='homeslider',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='sliders', to='Website.sliderposition', verbose_name='Display Locations'),
        ),
    ]
