# Generated by Django 6.0 on 2026-03-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_otpstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpstorage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otpstorage',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
