# Generated by Django 6.0 on 2025-12-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductImage',
            field=models.ImageField(upload_to='Product_Image/'),
        ),
    ]
