# Generated by Django 6.0 on 2026-01-09 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0005_profile_about_profile_designation_profile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board_Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_code', models.CharField(max_length=10, unique=True)),
                ('head_name', models.CharField(max_length=100, unique=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('headType', models.CharField(choices=[('1', 'Instituional Payment'), ('2', 'External Payment')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_Name', models.CharField(max_length=100, null=True, verbose_name='Program_Name')),
                ('Program_Code', models.CharField(max_length=100, null=True, verbose_name='Program_Code')),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session_Name', models.CharField(max_length=100, null=True, verbose_name='Session_Name')),
                ('Session_Code', models.CharField(max_length=100, null=True, verbose_name='Session_Code')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Received', 'Order Received'), ('Order Canceled', 'Order Canceled'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.country')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.state')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100, null=True)),
                ('mothers_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], default=None, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('religion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.religion')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_admission', models.DateField(blank=True, null=True)),
                ('student_id_no', models.CharField(editable=False, max_length=200, unique=True)),
                ('Admission_roll', models.IntegerField(null=True)),
                ('test_score', models.IntegerField(null=True)),
                ('merit_score', models.IntegerField(null=True)),
                ('merit_position', models.IntegerField(null=True)),
                ('Program_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.program')),
                ('Session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyShop.studentpersonal')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField()),
                ('paymentType', models.CharField(choices=[('1', 'One Time'), ('2', 'Monthy'), ('3', 'Semester'), ('4', 'Yearly'), ('5', 'Quarterly'), ('6', 'Half Yearly'), ('7', 'Anytime')], max_length=50)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('paymentHead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyShop.paymenthead')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyShop.studentpersonal')),
            ],
        ),
        migrations.CreateModel(
            name='EducationQSalualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationtype', models.CharField(choices=[('s', 'SSC'), ('h', 'HSC'), ('b', 'Bechelor'), ('M', 'Master')], max_length=20)),
                ('EducationLevel', models.CharField(max_length=100)),
                ('roll', models.IntegerField(null=True)),
                ('Result', models.FloatField(max_length=10, null=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.educationboard')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyShop.studentpersonal')),
            ],
        ),
        migrations.CreateModel(
            name='Upazilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.district')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Office', models.CharField(max_length=100, null=True, verbose_name='Permanant_Post_Office')),
                ('Village', models.CharField(max_length=100, null=True, verbose_name='Permanant_Village')),
                ('Present_Post_Office', models.CharField(max_length=100, null=True, verbose_name='Present_Post_Office')),
                ('Present_Village', models.CharField(max_length=100, null=True, verbose_name='Presemt_Village')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Permanant_Division', to='MyShop.state')),
                ('Present_District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Present_District', to='MyShop.district')),
                ('Present_Division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Present_Division', to='MyShop.state')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Permanant_District', to='MyShop.district')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyShop.studentpersonal')),
                ('Present_Upazilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Present_Upazilla', to='MyShop.upazilla')),
                ('upazilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Permanant_Upazilla', to='MyShop.upazilla')),
            ],
        ),
    ]
