# Generated by Django 6.0 on 2026-01-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0006_country_educationboard_paymenthead_program_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonal',
            name='birth_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonal',
            name='guardian_mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentpersonal',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled'), ('Order Received', 'Order Received'), ('Order Processing', 'Order Processing')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
