# Generated by Django 6.0 on 2026-01-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0007_studentpersonal_birth_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('On the way', 'On the way'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
