# Generated by Django 6.0 on 2026-01-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0010_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('On the way', 'On the way'), ('Order Received', 'Order Received')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='guardian_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='mobile',
            field=models.CharField(blank=True, null=True),
        ),
    ]
