# Generated by Django 6.0 on 2026-01-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0011_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='Division',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='state',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='studentaddress',
            old_name='Division',
            new_name='division',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
