# Generated by Django 6.0 on 2026-01-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0012_rename_state_division_rename_state_district_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Completed', 'Order Completed'), ('Order Received', 'Order Received'), ('On the way', 'On the way'), ('Order Canceled', 'Order Canceled')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
