# Generated by Django 6.0 on 2026-01-13 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0014_rename_district_upazilla_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Received', 'Order Received')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='Present_District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Present_District', to='MyShop.district'),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='Present_Division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Present_Division', to='MyShop.division'),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='Present_Upazilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Present_Upazilla', to='MyShop.upazilla'),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Permanant_District', to='MyShop.district'),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Permanant_Division', to='MyShop.division'),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='upazilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Permanant_Upazilla', to='MyShop.upazilla'),
        ),
    ]
