# Generated by Django 6.0 on 2026-01-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0015_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationqsalualification',
            old_name='Employee',
            new_name='student',
        ),
        migrations.AddField(
            model_name='educationqsalualification',
            name='registration_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='educationqsalualification',
            name='educationtype',
            field=models.CharField(choices=[('s', 'SSC'), ('h', 'HSC'), ('b', 'Bechelor'), ('d', 'Diploma'), ('m', 'Master')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
