# Generated by Django 6.0 on 2026-01-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0016_rename_employee_educationqsalualification_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
        migrations.CreateModel(
            name='EducationQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(choices=[('s', 'SSC'), ('h', 'HSC'), ('b', 'Bachelor'), ('d', 'Diploma'), ('m', 'Masters')], max_length=20)),
                ('education_group', models.CharField(choices=[('s', 'Science'), ('a', 'Arts'), ('c', 'Commerce'), ('t', 'Technical'), ('n', 'Nursing')], max_length=20)),
                ('education_name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(blank=True, null=True)),
                ('registration_no', models.IntegerField(blank=True, null=True)),
                ('result', models.FloatField(blank=True, null=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.educationboard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyShop.studentpersonal')),
            ],
        ),
        migrations.DeleteModel(
            name='EducationQSalualification',
        ),
    ]
