# Generated by Django 6.0 on 2026-01-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0017_alter_order_order_status_educationqualification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationqualification',
            old_name='education_name',
            new_name='institution_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Received', 'Order Received'), ('Order Processing', 'Order Processing')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
