# Generated by Django 6.0 on 2026-02-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0023_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Received', 'Order Received'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
