# Generated by Django 6.0 on 2026-02-09 17:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0024_alter_order_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_head_code', models.CharField(max_length=10, unique=True)),
                ('main_head_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalpaymenthead',
            name='headType',
            field=models.CharField(choices=[('1', 'Income'), ('2', 'Expense')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentpersonal',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled'), ('Order Received', 'Order Received'), ('On the way', 'On the way')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
        migrations.AlterField(
            model_name='paymenthead',
            name='headType',
            field=models.CharField(choices=[('1', 'Income'), ('2', 'Expense')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalMainHead',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('main_head_code', models.CharField(db_index=True, max_length=10)),
                ('main_head_name', models.CharField(db_index=True, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical main head',
                'verbose_name_plural': 'historical main heads',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalpaymenthead',
            name='payment_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MyShop.mainhead'),
        ),
        migrations.AddField(
            model_name='paymenthead',
            name='payment_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.mainhead'),
        ),
    ]
