# Generated by Django 6.0 on 2026-02-11 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0026_alter_order_order_status_feerate_historicalfeerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymentcontact',
            name='paymentHead',
        ),
        migrations.RemoveField(
            model_name='paymentcontact',
            name='paymentHead',
        ),
        migrations.AddField(
            model_name='historicalpaymentcontact',
            name='discount_type',
            field=models.CharField(choices=[('1', 'Flat Amount'), ('2', 'Percentage (%)')], default='1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentcontact',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentcontact',
            name='fees',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MyShop.feerate'),
        ),
        migrations.AddField(
            model_name='paymentcontact',
            name='discount_type',
            field=models.CharField(choices=[('1', 'Flat Amount'), ('2', 'Percentage (%)')], default='1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentcontact',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentcontact',
            name='fees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.feerate'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentcontact',
            name='contact_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaymentcontact',
            name='paymentType',
            field=models.CharField(choices=[('1', 'One Time'), ('2', 'Monthly'), ('3', 'Semester'), ('4', 'Yearly'), ('5', 'Quarterly'), ('6', 'Half Yearly'), ('7', 'Anytime')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Received', 'Order Received'), ('On the way', 'On the way'), ('Order Processing', 'Order Processing')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
        migrations.AlterField(
            model_name='paymentcontact',
            name='contact_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentcontact',
            name='paymentType',
            field=models.CharField(choices=[('1', 'One Time'), ('2', 'Monthly'), ('3', 'Semester'), ('4', 'Yearly'), ('5', 'Quarterly'), ('6', 'Half Yearly'), ('7', 'Anytime')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcontact',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.studentpersonal'),
        ),
    ]
