# Generated by Django 6.0 on 2026-02-11 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0027_remove_historicalpaymentcontact_paymenthead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationqualification',
            name='educational_file',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('Order Received', 'Order Received'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
        migrations.DeleteModel(
            name='HistoricalEducationQualification',
        ),
    ]
