# Generated by Django 6.0 on 2026-02-16 18:08

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0030_historicalsession_active_session_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('Order Received', 'Order Received'), ('On the way', 'On the way'), ('Order Processing', 'Order Processing'), ('Order Completed', 'Order Completed')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
        migrations.CreateModel(
            name='HistoricalEducationQualification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('education_type', models.CharField(choices=[('s', 'SSC'), ('h', 'HSC'), ('b', 'Bachelor'), ('d', 'Diploma'), ('m', 'Masters')], max_length=20)),
                ('education_group', models.CharField(choices=[('s', 'Science'), ('a', 'Arts'), ('c', 'Commerce'), ('t', 'Technical'), ('n', 'Nursing')], max_length=20)),
                ('course_name', models.CharField(max_length=100, null=True)),
                ('institution_name', models.CharField(max_length=100, null=True)),
                ('roll', models.IntegerField(blank=True, null=True)),
                ('registration_no', models.IntegerField(blank=True, null=True)),
                ('result', models.FloatField(blank=True, null=True)),
                ('passing_year', models.IntegerField(null=True)),
                ('educational_file', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('board', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MyShop.educationboard')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MyShop.studentpersonal')),
            ],
            options={
                'verbose_name': 'historical education qualification',
                'verbose_name_plural': 'historical education qualifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
