# Generated by Django 6.0 on 2026-02-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0035_historicalstudentadmission_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentadmission',
            name='student_id_no',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received'), ('Order Completed', 'Order Completed'), ('On the way', 'On the way')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='student_id_no',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
