# Generated by Django 6.0 on 2026-02-26 19:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0036_alter_historicalstudentadmission_student_id_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received'), ('On the way', 'On the way')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
        migrations.CreateModel(
            name='HistoricalStudentPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('payment_date', models.DateField(null=True)),
                ('paymentType', models.CharField(choices=[('1', 'Partial'), ('2', 'Full Payment')], max_length=50, null=True)),
                ('discount_type', models.CharField(choices=[('1', 'Flat Amount'), ('2', 'Percentage (%)')], default='1', max_length=20, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fees', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MyShop.feerate')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MyShop.studentpersonal')),
            ],
            options={
                'verbose_name': 'historical student payment',
                'verbose_name_plural': 'historical student payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(null=True)),
                ('paymentType', models.CharField(choices=[('1', 'Partial'), ('2', 'Full Payment')], max_length=50, null=True)),
                ('discount_type', models.CharField(choices=[('1', 'Flat Amount'), ('2', 'Percentage (%)')], default='1', max_length=20, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('fees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.feerate')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyShop.studentpersonal')),
            ],
        ),
    ]
