# Generated by Django 6.0 on 2026-02-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0037_alter_order_order_status_historicalstudentpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentpayment',
            name='new_due',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalstudentpayment',
            name='old_due',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalstudentpayment',
            name='total_paid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='new_due',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='old_due',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='total_paid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
