# Generated by Django 6.0 on 2026-02-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0038_historicalstudentpayment_new_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentpayment',
            name='payment_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='payment_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled'), ('On the way', 'On the way'), ('Order Received', 'Order Received'), ('Order Processing', 'Order Processing')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
