# Generated by Django 6.0 on 2026-03-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0039_historicalstudentpayment_payment_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentpayment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('On the way', 'On the way'), ('Order Processing', 'Order Processing'), ('Order Completed', 'Order Completed'), ('Order Received', 'Order Received')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
