# Generated by Django 6.0 on 2026-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0040_historicalstudentpayment_invoice_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentcontact',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentcontact',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
