# Generated by Django 6.0 on 2026-03-02 17:15

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0041_historicalpaymentcontact_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcontact',
            options={'ordering': ['-contact_date', '-id'], 'verbose_name': 'Payment Contact', 'verbose_name_plural': 'Payment Contacts'},
        ),
        migrations.AddField(
            model_name='paymentcontact',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received'), ('On the way', 'On the way')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
        migrations.AlterField(
            model_name='paymentcontact',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentcontact',
            name='contact_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcontact',
            name='discount_type',
            field=models.CharField(choices=[('1', 'Flat (TK)'), ('2', 'Percent (%)')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentcontact',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentcontact',
            name='fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_contacts', to='MyShop.feerate'),
        ),
        migrations.AlterField(
            model_name='paymentcontact',
            name='paymentType',
            field=models.CharField(choices=[('1', 'One Time'), ('2', 'Monthly'), ('4', 'Yearly'), ('7', 'Anytime')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentcontact',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paymentcontact',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_contacts', to='MyShop.studentpersonal'),
        ),
        migrations.DeleteModel(
            name='HistoricalPaymentContact',
        ),
    ]
