# Generated by Django 6.0 on 2026-03-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0047_institution_educationqualification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Received', 'Order Received'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled'), ('On the way', 'On the way')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
