# Generated by Django 6.0 on 2026-03-14 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('MyShop', '0050_account_historicalstudentpayment_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentpayment',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Accounts.account'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='Accounts.account'),
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='HistoricalAccount',
        ),
    ]
