# Generated by Django 6.0 on 2026-03-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0056_employeeprofile_first_name_employeeprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Received', 'Order Received'), ('On the way', 'On the way'), ('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
