# Generated by Django 6.0 on 2026-03-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0068_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.IntegerField(default=0, help_text='Enter a number to sort categories (e.g., 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='designation',
            name='order',
            field=models.IntegerField(default=0, help_text='Enter a number to sort categories (e.g., 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='order',
            field=models.IntegerField(default=0, help_text='Enter a number to sort categories (e.g., 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='historicaldesignation',
            name='order',
            field=models.IntegerField(default=0, help_text='Enter a number to sort categories (e.g., 1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')], default='Order Received', max_length=22, verbose_name={('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received')}),
        ),
    ]
