# Generated by Django 6.0 on 2026-03-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customer_productcategory_accounttransaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalAccount',
        ),
    ]
